@startuml
title "test-project"

package "motivation" #FFE4E1 {
  component "Manage Personal Tasks" as motivation_goal_manage_tasks
}

package "business" #E6F3FF {
  component "End User" as business_actor_end_user
  component "Create Task Process" as business_businessprocess_create_task_process
  component "Task Management Service" as business_businessservice_task_management
}

package "application" #E6FFE6 {
  component "Todo API Service" as application_applicationservice_todo_api_service
}

package "api" #F0E6FF {
  component "List Todos" as api_operation_list_todos
  component "Create Todo" as api_operation_create_todo
  component "Update Todo" as api_operation_update_todo
  component "Delete Todo" as api_operation_delete_todo
}

package "data-model" #E6F0FF {
  component "Todo Object" as data_model_entity_todo_object
}

package "data-store" #FFE6F0 {
  component "Id Column" as data_store_column_todos_id_column
  component "Title Column" as data_store_column_todos_title_column
  component "Done Column" as data_store_column_todos_done_column
  component "Todos Table" as data_store_table_todos_table
}


@enduml
