# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# Disable specific rules
MD013: false # Line length - we have long code examples
MD033: false # Inline HTML - we use HTML for badges and complex formatting
MD034: false # Bare URLs - sometimes needed in documentation
MD041: false # First line in file should be top-level heading - not always applicable

# Configure specific rules
MD007:
  indent: 2 # Unordered list indentation

MD024:
  allow_different_nesting: true # Allow duplicate headings in different sections

MD025:
  front_matter_title: "" # Don't require front matter

MD029:
  style: "ordered" # Ordered list item prefix style

MD046:
  style: "fenced" # Code block style
