name: "Advanced Operations"
description: "Test project, migrate, and other advanced functionality"
priority: medium

pipelines:
  - name: "Projection operations"
    steps:
      - command: "add motivation goal project-test-goal --name 'Goal for Projection' --description 'Goal that will be projected'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "delete motivation.goal.project-test-goal --force"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

  - name: "Trace dependencies for element"
    steps:
      - command: "add data-store collection trace-test-table --name 'trace_collection' --description 'Collection for tracing'"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/collections.yaml
        expect_exit_code: 0

      - command: "add data-store field trace-test-column --name 'trace_field' --description 'Field for tracing'"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/fields.yaml
        expect_exit_code: 0

      - command: "relationship add data-store.collection.trace-test-table data-store.field.trace-test-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "trace data-store.collection.trace-test-table"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "data-store.collection.trace-test-table"

      - command: "delete data-store.collection.trace-test-table --force"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/collections.yaml
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete data-store.field.trace-test-column --force"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/fields.yaml
        expect_exit_code: 0

  - name: "Model information and statistics"
    steps:
      - command: "info"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "model"
          - "motivation"

      - command: "conformance"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "conformance"

  - name: "Migrate model version"
    steps:
      - command: "migrate --check"
        files_to_compare: []
        expect_exit_code: 1

      - command: "version"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "CLI Version"

  - name: "Element operations via element command"
    steps:
      - command: "add motivation goal element-cmd-test --name 'Element Command Test' --description 'Test via element command'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "show motivation.goal.element-cmd-test"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "motivation.goal.element-cmd-test"

      - command: "delete motivation.goal.element-cmd-test --force"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

  - name: "Relationship operations via relationship command"
    steps:
      - command: "add data-store collection rel-cmd-table --name 'rel_collection' --description 'Collection for relationship command test'"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/collections.yaml
        expect_exit_code: 0

      - command: "add data-store field rel-cmd-column --name 'rel_field' --description 'Field for relationship command test'"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/fields.yaml
        expect_exit_code: 0

      - command: "relationship add data-store.collection.rel-cmd-table data-store.field.rel-cmd-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "relationship show data-store.collection.rel-cmd-table data-store.field.rel-cmd-column"
        files_to_compare: []
        expect_exit_code: 0

      - command: "relationship delete data-store.collection.rel-cmd-table data-store.field.rel-cmd-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete data-store.collection.rel-cmd-table --force"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/collections.yaml
        expect_exit_code: 0

      - command: "delete data-store.field.rel-cmd-column --force"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/fields.yaml
        expect_exit_code: 0
