name: "Advanced Operations"
description: "Test project, migrate, and other advanced functionality"
priority: medium

pipelines:
  - name: "Projection operations"
    steps:
      - command: "add motivation goal project-test-goal --name 'Goal for Projection' --description 'Goal that will be projected'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "delete motivation.goal.project-test-goal --force"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

  - name: "Trace dependencies for element"
    steps:
      - command: "add datastore table trace-test-table --name 'trace_table' --description 'Table for tracing'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
        expect_exit_code: 0

      - command: "add datastore column trace-test-column --name 'trace_col' --description 'Column for tracing'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

      - command: "relationship add datastore.table.trace-test-table datastore.column.trace-test-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "trace datastore.table.trace-test-table"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "datastore.table.trace-test-table"

      - command: "delete datastore.table.trace-test-table --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete datastore.column.trace-test-column --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

  - name: "Model information and statistics"
    steps:
      - command: "info"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "model"
          - "motivation"

      - command: "conformance"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "conformance"

  - name: "Migrate model version"
    steps:
      - command: "migrate --check"
        files_to_compare: []
        expect_exit_code: 1

      - command: "version"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "CLI Version"

  - name: "Element operations via element command"
    steps:
      - command: "element add motivation goal element-cmd-test --name 'Element Command Test' --description 'Test via element command'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "element show motivation.goal.element-cmd-test"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "motivation.goal.element-cmd-test"

      - command: "element delete motivation.goal.element-cmd-test --force"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

  - name: "Relationship operations via relationship command"
    steps:
      - command: "add datastore table rel-cmd-table --name 'rel_table' --description 'Table for relationship command test'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
        expect_exit_code: 0

      - command: "add datastore column rel-cmd-column --name 'rel_col' --description 'Column for relationship command test'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

      - command: "relationship add datastore.table.rel-cmd-table datastore.column.rel-cmd-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "relationship show datastore.table.rel-cmd-table datastore.column.rel-cmd-column"
        files_to_compare: []
        expect_exit_code: 0

      - command: "relationship delete datastore.table.rel-cmd-table datastore.column.rel-cmd-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete datastore.table.rel-cmd-table --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
        expect_exit_code: 0

      - command: "delete datastore.column.rel-cmd-column --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0
