name: "Element CRUD Operations"
description: "Test add, update, delete operations for elements across layers"
priority: high

pipelines:
  - name: "Add and update motivation goal"
    steps:
      - command: "add motivation goal test-goal --name 'Test Strategic Goal' --description 'Test goal for verification'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-goal"

      - command: "update motivation.goal.test-goal --name 'Updated Strategic Goal'"
        files_to_compare:
          - 01_motivation/goals.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete motivation.goal.test-goal --force"
        files_to_compare:
          - 01_motivation/goals.yaml
          - manifest.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"
          - "test-goal"

  - name: "Add business service with update"
    steps:
      - command: "add business service test-service --name 'Test Business Service' --description 'Temporary test service'"
        files_to_compare:
          - manifest.yaml
          - 02_business/services.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-service"

      - command: "update business.service.test-service --name 'Updated Business Service'"
        files_to_compare:
          - 02_business/services.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete business.service.test-service --force"
        files_to_compare:
          - manifest.yaml
          - 02_business/services.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add application component lifecycle"
    steps:
      - command: "add application component test-component --name 'Test Component' --description 'Test application component'"
        files_to_compare:
          - manifest.yaml
          - 04_application/components.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-component"

      - command: "show application.component.test-component"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "test-component"
          - "Test Component"

      - command: "update application.component.test-component --name 'Updated Component'"
        files_to_compare:
          - 04_application/components.yaml
        expect_exit_code: 0

      - command: "delete application.component.test-component --force"
        files_to_compare:
          - manifest.yaml
          - 04_application/components.yaml
        expect_exit_code: 0

  - name: "Add technology node with update"
    steps:
      - command: "add technology node test-node --name 'Test Node' --description 'Test infrastructure node'"
        files_to_compare:
          - manifest.yaml
          - 05_technology/nodes.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-node"

      - command: "update technology.node.test-node --name 'Updated Node'"
        files_to_compare:
          - 05_technology/nodes.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete technology.node.test-node --force"
        files_to_compare:
          - manifest.yaml
          - 05_technology/nodes.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add security role with update"
    steps:
      - command: "add security role test-role --name 'Test Security Role' --description 'Test security role'"
        files_to_compare:
          - manifest.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-role"

      - command: "update security.role.test-role --name 'Updated Security Role'"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete security.role.test-role --force"
        files_to_compare:
          - manifest.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add API operation with update"
    steps:
      - command: 'add api operation test-operation --name ''Test Operation'' --description ''GET /api/test'' --properties ''{"method":"GET","path":"/api/test"}'''
        files_to_compare:
          - manifest.yaml
          - 06_api/operations.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-operation"

      - command: "update api.operation.test-operation --name 'Updated Operation'"
        files_to_compare:
          - 06_api/operations.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete api.operation.test-operation --force"
        files_to_compare:
          - manifest.yaml
          - 06_api/operations.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add data model schema with update"
    steps:
      - command: "add data-model objectschema test-schema --name 'TestSchema' --description 'Test object schema'"
        files_to_compare:
          - manifest.yaml
          - 07_data-model/objectschemas.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-schema"

      - command: "update data-model.objectschema.test-schema --name 'UpdatedSchema'"
        files_to_compare:
          - 07_data-model/objectschemas.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete data-model.objectschema.test-schema --force"
        files_to_compare:
          - manifest.yaml
          - 07_data-model/objectschemas.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add datastore collection with update"
    steps:
      - command: "add data-store collection test-table --name 'test_collection' --description 'Test collection'"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/collections.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-table"

      - command: "update data-store.collection.test-table --name 'updated_collection'"
        files_to_compare:
          - 08_data-store/collections.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete data-store.collection.test-table --force"
        files_to_compare:
          - manifest.yaml
          - 08_data-store/collections.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add UX view with update"
    steps:
      - command: "add ux view test-view --name 'Test View' --description 'Test user interface view'"
        files_to_compare:
          - manifest.yaml
          - 09_ux/views.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-view"

      - command: "update ux.view.test-view --name 'Updated View'"
        files_to_compare:
          - 09_ux/views.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete ux.view.test-view --force"
        files_to_compare:
          - manifest.yaml
          - 09_ux/views.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add navigation route with update"
    steps:
      - command: 'add navigation route test-route --name ''Test Route'' --description ''Test navigation route'' --properties ''{"path":"/test"}'''
        files_to_compare:
          - manifest.yaml
          - 10_navigation/routes.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-route"

      - command: "update navigation.route.test-route --name 'Updated Route'"
        files_to_compare:
          - 10_navigation/routes.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete navigation.route.test-route --force"
        files_to_compare:
          - manifest.yaml
          - 10_navigation/routes.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add APM metric instrument with update"
    steps:
      - command: "add apm metricinstrument test-metric --name 'Test Metric' --description 'Test observability metric instrument'"
        files_to_compare:
          - manifest.yaml
          - 11_apm/metricinstruments.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-metric"

      - command: "update apm.metricinstrument.test-metric --name 'Updated Metric'"
        files_to_compare:
          - 11_apm/metricinstruments.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete apm.metricinstrument.test-metric --force"
        files_to_compare:
          - manifest.yaml
          - 11_apm/metricinstruments.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

  - name: "Add testing test case sketch with update"
    steps:
      - command: "add testing testcasesketch test-case --name 'Test Case' --description 'Test case sketch for verification'"
        files_to_compare:
          - manifest.yaml
          - 12_testing/testcasesketchs.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "test-case"

      - command: "update testing.testcasesketch.test-case --name 'Updated Test Case'"
        files_to_compare:
          - 12_testing/testcasesketchs.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Updated"

      - command: "delete testing.testcasesketch.test-case --force"
        files_to_compare:
          - manifest.yaml
          - 12_testing/testcasesketchs.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"
