name: "Relationship Management"
description: "Test relationship creation, modification, and deletion operations"
priority: high

pipelines:
  - name: "Create and delete relationships"
    steps:
      - command: "relationship list"
        files_to_compare: []
        expect_exit_code: 0
        expect_stdout_contains:
          - "relationship"

      - command: "add motivation goal relationship-test-goal --name 'Test Goal for Relations' --description 'Goal for testing relationships'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "add business service relationship-test-service --name 'Test Service for Relations' --description 'Service for testing relationships'"
        files_to_compare:
          - manifest.yaml
          - 02_business/services.yaml
        expect_exit_code: 0

      - command: "relationship add relationship-test-goal realizes relationship-test-service"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"
          - "relationship"

      - command: "relationship delete relationship-test-goal realizes relationship-test-service"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"
          - "relationship"

      - command: "delete relationship-test-goal --force"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "delete relationship-test-service --force"
        files_to_compare:
          - manifest.yaml
          - 02_business/services.yaml
        expect_exit_code: 0

  - name: "Multiple relationship types"
    steps:
      - command: "add motivation goal multi-rel-goal --name 'Multi Relationship Goal' --description 'Test multiple relationship types'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "add business service multi-rel-service --name 'Multi Relationship Service' --description 'Test multiple relationship types'"
        files_to_compare:
          - manifest.yaml
          - 02_business/services.yaml
        expect_exit_code: 0

      - command: "add application component multi-rel-component --name 'Multi Relationship Component' --description 'Test multiple relationship types'"
        files_to_compare:
          - manifest.yaml
          - 04_application/components.yaml
        expect_exit_code: 0

      - command: "relationship add multi-rel-goal realizes multi-rel-service"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "relationship add multi-rel-service implements multi-rel-component"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "relationship list"
        files_to_compare: []
        expect_exit_code: 0

      - command: "delete multi-rel-goal --force"
        files_to_compare:
          - manifest.yaml
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete multi-rel-service --force"
        files_to_compare:
          - manifest.yaml
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete multi-rel-component --force"
        files_to_compare:
          - manifest.yaml
          - 04_application/components.yaml
        expect_exit_code: 0
