name: "Relationship Management"
description: "Test relationship creation, modification, and deletion operations"
priority: high

pipelines:
  - name: "Create and delete relationships"
    steps:
      - command: "add motivation goal rel-base-goal --name 'Baseline Goal' --description 'Goal for relationships'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "relationship list rel-base-goal"
        files_to_compare: []
        expect_exit_code: 0

      - command: "add datastore table rel-test-table --name 'test_table' --description 'Table for relationship test'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
        expect_exit_code: 0

      - command: "add datastore column rel-test-column --name 'test_column' --description 'Column for relationship test'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

      - command: "relationship add rel-test-table rel-test-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Added"

      - command: "relationship delete rel-test-table rel-test-column --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0
        expect_stdout_contains:
          - "Deleted"

      - command: "delete rel-test-table --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete rel-test-column --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

      - command: "delete rel-base-goal --force"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

  - name: "Multiple relationship types"
    steps:
      - command: "add datastore table multi-rel-table --name 'multi_table' --description 'Table for multi-relationship test'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
        expect_exit_code: 0

      - command: "add datastore column multi-rel-col-1 --name 'column_1' --description 'First column'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

      - command: "add datastore column multi-rel-col-2 --name 'column_2' --description 'Second column'"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

      - command: "relationship add multi-rel-table multi-rel-col-1 --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "relationship add multi-rel-table multi-rel-col-2 --predicate composes"
        files_to_compare:
          - relationships.yaml
        expect_exit_code: 0

      - command: "relationship list multi-rel-table"
        files_to_compare: []
        expect_exit_code: 0

      - command: "delete multi-rel-table --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/tables.yaml
          - relationships.yaml
        expect_exit_code: 0

      - command: "delete multi-rel-col-1 --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

      - command: "delete multi-rel-col-2 --force"
        files_to_compare:
          - manifest.yaml
          - 08_datastore/columns.yaml
        expect_exit_code: 0

  - name: "Negative test: Cross-layer relationships not supported"
    description: "Verify that cross-layer relationships (higher→lower) are properly rejected or handled by the CLI"
    steps:
      - command: "add motivation goal cross-layer-goal --name 'Cross Layer Goal' --description 'Goal for cross-layer test'"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "add business service cross-layer-service --name 'Cross Layer Service' --description 'Service for cross-layer test'"
        files_to_compare:
          - manifest.yaml
          - 02_business/services.yaml
        expect_exit_code: 0

      - command: "relationship add cross-layer-goal cross-layer-service --predicate realizes"
        files_to_compare: []
        expect_exit_code: 1
        expect_stderr_contains:
          - "cannot add cross-layer relationship"

      - command: "delete cross-layer-goal --force"
        files_to_compare:
          - manifest.yaml
          - 01_motivation/goals.yaml
        expect_exit_code: 0

      - command: "delete cross-layer-service --force"
        files_to_compare:
          - manifest.yaml
          - 02_business/services.yaml
        expect_exit_code: 0
