#!/usr/bin/env tsx

/**
 * Generate OpenAPI specification from visualization server
 * Exports the spec to docs/api-spec.yaml for documentation and static serving
 */

import { writeFile } from "fs/promises";
import { VisualizationServer } from "../src/server/server.js";
import { Model } from "../src/core/model.js";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import * as YAML from "yaml";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = dirname(dirname(__filename));

async function generateOpenAPISpec() {
  try {
    console.log("🔨 Generating OpenAPI specification...");

    // Load model
    console.log("📦 Loading model...");
    const model = await Model.load(projectRoot, { lazyLoad: true });

    // Create server instance
    console.log("🚀 Creating server instance...");
    const server = new VisualizationServer(model, { authEnabled: false });

    // Get the OpenAPI spec from the server using public API
    const spec = server.getOpenAPIDocument({
      openapi: "3.1.0",
      info: {
        title: "Documentation Robotics Visualization Server API",
        version: "0.1.0",
        description: "API specification for the DR CLI visualization server",
        contact: {
          name: "Documentation Robotics",
          url: "https://github.com/tinkermonkey/documentation_robotics",
        },
        license: {
          name: "ISC",
        },
      },
      servers: [
        { url: "http://localhost:8080", description: "Local development server" },
      ],
    });

    // Convert to valid YAML using the yaml package
    const specYaml = `# AUTO-GENERATED: This file is automatically generated from route definitions.
# DO NOT EDIT MANUALLY - your changes will be overwritten.
# To regenerate this file, run: npm run generate:openapi from the cli/ directory.
# This ensures the spec is always in sync with the actual server implementation.

${YAML.stringify(spec, { indent: 2 })}
`;

    // Write spec to file (to repo root docs/, not cli/docs/)
    const outputPath = join(projectRoot, "..", "docs", "api-spec.yaml");
    console.log(`📝 Writing OpenAPI spec to ${outputPath}...`);
    await writeFile(outputPath, specYaml, "utf-8");

    console.log("✅ OpenAPI specification generated successfully!");
    console.log(`📄 Spec location: ${outputPath}`);
    console.log("🌐 View spec at: http://localhost:8080/api-docs");
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("❌ Failed to generate OpenAPI specification:", message);
    if (error instanceof Error && error.stack) {
      console.error(error.stack);
    }
    process.exit(1);
  }
}

generateOpenAPISpec();
