# Valid UX layer fixture - LibraryComponent, UXSpec, and View with source references
# Tests: Source reference validation for UX components, specs, and views
# Note: Backward compatibility verified - existing fixtures without source references continue to validate

library-components:
  - id: "09-library-component-order-form"
    name: "OrderFormComponent"
    type: "form-field"
    label: "Order Form"
    description: "Reusable order form component with validation"
    category: "forms"
    source:
      reference:
        provenance: "extracted"
        locations:
          - file: "src/components/OrderForm.tsx"
            symbol: "OrderForm"
        repository:
          url: "https://github.com/acme/web-frontend.git"
          commit: "abc123def4567890abcdef1234567890abcdef12"

  - id: "09-library-component-data-table"
    name: "DataTableComponent"
    type: "table"
    label: "Data Table"
    description: "Configurable data table with sorting and filtering"
    category: "data-display"
    source:
      reference:
        provenance: "manual"
        locations:
          - file: "src/components/DataTable/DataTable.vue"
            symbol: "DataTable"
          - file: "src/components/DataTable/useTableSort.ts"
            symbol: "useTableSort"

  - id: "09-library-component-chart"
    name: "SalesChartComponent"
    type: "chart"
    label: "Sales Chart"
    description: "Interactive sales data visualization"
    category: "charts"
    source:
      reference:
        provenance: "inferred"
        locations:
          - file: "src/components/charts/SalesChart.jsx"

ux-specs:
  - id: "09-ux-spec-order-management"
    name: "OrderManagementExperience"
    version: "1.2.0"
    experience: "order-mgmt-ux"
    title: "Order Management Experience"
    description: "Complete UX specification for order management workflow"
    source:
      reference:
        provenance: "extracted"
        locations:
          - file: "src/specs/OrderManagementSpec.ts"
            symbol: "orderManagementSpec"
        repository:
          url: "https://github.com/acme/ux-definitions.git"
          commit: "def456789abcdef0123456789abcdef012345678"

  - id: "09-ux-spec-customer-dashboard"
    name: "CustomerDashboardExperience"
    version: "2.0.1"
    experience: "dashboard-ux"
    title: "Customer Dashboard"
    description: "Main customer dashboard experience with widgets"
    source:
      reference:
        provenance: "manual"
        locations:
          - file: "src/specs/DashboardSpec.yaml"

views:
  - id: "09-view-order-list"
    name: "OrderListView"
    type: "list"
    title: "Order List"
    description: "Displays paginated list of orders with search and filters"
    routable: true
    layout: "main-content-layout"
    source:
      reference:
        provenance: "extracted"
        locations:
          - file: "src/views/orders/OrderListView.tsx"
            symbol: "OrderListView"
        repository:
          url: "https://github.com/acme/web-frontend.git"
          commit: "abc123def4567890abcdef1234567890abcdef12"

  - id: "09-view-order-detail"
    name: "OrderDetailView"
    type: "detail"
    title: "Order Detail"
    description: "Detailed view of a single order with edit capabilities"
    routable: true
    layout: "detail-layout"
    source:
      reference:
        provenance: "extracted"
        locations:
          - file: "src/views/orders/OrderDetailView.tsx"
            symbol: "OrderDetailView"
          - file: "src/views/orders/OrderDetailView.tsx"
            symbol: "OrderDetailView.handleSubmit"

  - id: "09-view-dashboard"
    name: "CustomerDashboardView"
    type: "dashboard"
    title: "Dashboard"
    description: "Main dashboard with sales metrics and charts"
    routable: true
    source:
      reference:
        provenance: "manual"
        locations:
          - file: "src/views/DashboardView.vue"
            symbol: "DashboardView"
